billing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from inventory import urls
from inventory.views import *

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', index),
    path('inventory/', include(urls)),
    path('cash_form/', cashform, name='cashform'),
    path('denomination_modal/', denomination_modal, name='d_modal'),
    path('billing_form/', billing_counter_form, name='counterform'),
    path('dashboard/<int:id>/',dashboard,name = 'dash'),
    path('dashboard/payment/<int:bid>',customer_payment,name="c_payment"),
    path('grid/<slug:bill>',grid,name ='grid'),

    path('startup_form/',startup_form,name="start_form"),
    path('main_dash/<slug:bill>/',main_dash,name='maindash'),

]
urlpatterns += [
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                          document_root=settings.STATIC_ROOT)

inventory/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class SellerDetails(models.Model):
    gstin = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    id_card = models.CharField(max_length=50)
    registered_on = models.DateField()
    valid_till = models.DateField()


class Seller(models.Model):
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15)
    details = models.OneToOneField(SellerDetails, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


gender_choice = [('M', 'Male'), ('F', 'Female'), ('O', 'Others')]


class Attendee(models.Model):
    name = models.CharField(max_length=100)
    image = models.FileField(upload_to='pics/')
    age = models.IntegerField()
    gender = models.CharField(choices=gender_choice, max_length=2)
    mobile = models.CharField(max_length=15)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=100, blank=True)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, blank=True)

    def __str__(self):
        return self.name


class Brands(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ShelfId(models.Model):
    shelf_id = models.CharField(max_length=4)


class Shelf(models.Model):
    name = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Category(models.Model):
    type_of = models.CharField(max_length=100)
    life_span = models.DurationField()

    def __str__(self):
        return self.type_of


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    expiry = models.DateField(blank=True, null=True)
    added_on = models.DateField(null=True)
    bar_code = models.CharField(unique=True, max_length=25)
    weight = models.IntegerField(blank=True, null=True)
    size = models.CharField(blank=True, max_length=5)
    category = models.ForeignKey(Category, related_name="category", on_delete=models.PROTECT)
    brand = models.ForeignKey(Brands, on_delete=models.PROTECT, related_name="brand")
    shelf = models.ForeignKey(Shelf, on_delete=models.PROTECT, related_name="shelf")
    seller = models.ForeignKey(Seller, related_name="seller", on_delete=models.PROTECT)
    shelf_code = models.ForeignKey(ShelfId, related_name="shelf_code", on_delete=models.PROTECT)

    def __str__(self):
        return "%s %s" % (self.brand, self.name)


class Denomination(models.Model):
    name = models.CharField(max_length=20)
    value = models.IntegerField(unique=True)

    def __str__(self):
        return str(self.value)


class ProductAddition(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_addition', blank=True,
                                null=True)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=2)
    name = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.product.name


class Cart(models.Model):
    product = models.ManyToManyField(ProductAddition, related_name='product_cart')
    amount = models.DecimalField(decimal_places=2, max_digits=10)


class BillingCounter(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    counter_id = models.CharField(max_length=10)
    opening_balance = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.counter_id

    def cash_objects(self):
        return self.cash_set.all()


class Cash(models.Model):
    billing_counter = models.CharField(max_length=100,blank=True,null=True)
    note_type = models.ForeignKey(Denomination, on_delete=models.CASCADE, null=True)
    counts = models.IntegerField(null=True)
    date = models.DateTimeField(default=timezone.now(),editable=False)
    is_customer = models.BooleanField(default=False)
    opening = models.BooleanField(default=False)
    current = models.BooleanField(default=False)
    pay_amt = models.BooleanField(default=False)
    return_amt = models.BooleanField(default=False)
    login_unique = models.CharField(max_length=100,blank=True,null=True)
    trans_id = models.CharField(max_length=100,blank=True,null=True)
    reverted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.note_type.value)

class Amount(models.Model):
    date = models.DateTimeField(default=timezone.now(),editable=False)
    login_unique = models.CharField(max_length=100,blank=True,null=True)
    amount = models.DecimalField(max_digits=10,decimal_places=2)
    opening = models.BooleanField(default=False)
    current = models.BooleanField(default=False)

    def __str__(self):
        return self.login_unique


class Transaction(models.Model):
    customer = models.CharField(max_length=100,blank=True,null=True)
    mobile = models.CharField(max_length=15,null=True)
    date = models.DateTimeField(default=timezone.now(),editable=False)


class Checkout(models.Model):
    system_used = models.ForeignKey(BillingCounter, on_delete=models.PROTECT)
    cart = models.ForeignKey(Cart, on_delete=models.PROTECT)
    date = models.DateField()
    # customer_cash = models.ForeignKey(DispensedCash, on_delete=models.PROTECT)
    customer_name = models.CharField(max_length=100, blank=True, null=True)
    customer_mob = models.CharField(max_length=15, blank=True, null=True)
    amount_return = models.ManyToManyField(Cash)

templates/attendee_registration.html
{% extends 'base.html' %}

{% block title %} attendee registration {% endblock %}
{% block content %}
<h1>attendee registration</h1>

<form  method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% for field in form %}


                                <dl>           <dt>{{ field.label_tag }}
                                        {% if field.field.required %}<span class="error"> * </span>{% endif %}
                                    </dt>
                                    <dd>{{ field }}</dd>
                                    {% if field.help_text %}
                                        <dd>{{ field.help_text }}</dd>{% endif %}
                                    {% if field.errors %}
                                        <div class="error">{{ field.errors }} </div>{% endif %}
                                    </dl>

        {% endfor %}
  <input type="submit" name="" value="Register">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/security_assets/css/formset.css">
    <link rel="stylesheet" href="/static/security_assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/security_assets/css/font-awesome.min.css">
    {% block extracss %}
    {% endblock %}
   </head>
  <body>

    {% block content %}

    {% endblock %}

    {{ formset.media }}
<script src="/static/security_assets/js/vendor/jquery-2.2.4.min.js"></script>
<script src="/static/security_assets/js/jquery.formset.js"></script>
<!-- bootstrap 4 js -->
<script src="/static/security_assets/js/bootstrap.min.js"></script>
{% block extrajs %}
{% endblock %}
  </body>
</html>

templates/c_payment.html
{% extends 'base.html' %}
{% block content %}
<h2>payment</h2>
<form  method="post">
  {% csrf_token %}
  {% for field in form %}
      <div class="form-group row">
          <div class="col-sm-4">
              {{ field.label_tag }}
              {% if field.field.required %}
                  <span class="text-danger">*</span>
              {% endif %}<br>
          </div>
          {% if field.name == 'product'  %}
          {{field}}
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
              Add
          </button>
          {% else %}
          <div class="col-sm-8">
              {{ field }}
          </div>
          {% endif %}
      </div>
      {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
      {% endfor %}
  {% endfor %}
  {{form.management_form}}
  <input type="submit" name="" value="payment">
</form>



{% endblock %}

templates/cashform.html
{% extends 'base.html' %}
{% block content %}

<h1>cash form</h1>
<form  method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group row">
        <div class="col-sm-4">
            {{ field.label_tag }}
            {% if field.field.required %}
            <span class="text-danger">*</span>
            {% endif %}<br>
        </div>
        <div class="col-sm-8">
            {% if field.name == 'note_type' %}
            {{ field }}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add
            </button>
            {% else %}
            {{ field }}
            {% endif %}
        </div>
    </div>
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    {% endfor %}
    <input type="submit" name="" value="submit">
</form>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Denomination form</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="denomination" action="/denomination_modal/" method="post">
                  {% csrf_token %}
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="" value="" required>
                    <p></p>
                    <label for="value">Value:</label>
                    <input type="number" id="value" name="" value="" required >

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" onclick="doAsyncPost()" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}

<script>
  function doAsyncPost(){
    var name = $("#name").val();
    var value = $("#value").val();
    $.ajax({
      url:'/denomination_modal/',
      type:'POST',
      data:{
        'name':name,
        'value':value
      },
      dataType:'json',
      success: function(data, status, xhr) {
          if (data.is_taken) {
            alert("A denomination type already exists.");
          }
        }
    });
  }

</script>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% block content %}
<h1>checkout</h1>
<form  method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group row">
      <div class="col-sm-4">
          {{ field.label_tag }}
          {% if field.field.required %}
              <span class="text-danger">*</span>
          {% endif %}<br>
      </div>
      {% if field.name == 'billing_counter' %}
      {{field}} <button type="button" name="button">Add </button>

      <div class="col-sm-8">
          {{ field }}
      </div>
  
  </div>
  {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
  {% endfor %}

  {% endfor %}
  <select class="form-control" multiple="multiple">
  <option selected="selected">orange</option>
  <option>white</option>
  <option selected="selected">purple</option>
  </select>
</form>

{% endblock %}

templates/counter_form.html
{% extends 'base.html' %}
{% block content %}

<h1>billing counter</h1>
<form id="formsubmit" method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group row">
      <div class="col-sm-4 ">
          {{ field.label_tag }}
          {% if field.field.required %}
              <span class="text-danger">*</span>
          {% endif %}<br>
      </div>
      <div class="col-sm-8">
          {{ field }}
      </div>
  </div>
  {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
  {% endfor %}

  {% endfor %}
  {{ formset.management_form }}

<div id="looper">
  {% for field in formset %}
  <div class="form-group row">
      <div class="col-sm-4">
          {{ field.label_tag }}
          {% if field.field.required %}
              <span class="text-danger">*</span>
          {% endif %}<br>
      </div>

        <div class="col-sm-8">
            {{ field }}
        </div>
  </div>

  {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
  {% endfor %}

  {% endfor %}
  </div>


</form>

<button type="button" onclick="submit()">Submit</button>



{% endblock %}

{% block extrajs %}


<script>
function submit(){
  var looper=$("#looper");
  var inputs =looper.find("input");
  var selects = looper.find("select");
  console.log(inputs);
  console.log(selects);
  var total = 0;
  var newinp = [];
  var cc = 0;
  for(var i=0;i<inputs.length;i++){

      console.log($(inputs[i]).attr("id"));
      if ($(inputs[i]).attr("id").endsWith("counts")) {
        newinp[cc] = parseInt($(inputs[i]).val());
        cc++;
      }

  }
  console.log(newinp);
  for(var i=0;i<selects.length;i++){
    var sid=$(selects[i]).attr("id");

    var iid=$(inputs[i]).attr("id");

    var count = 1;
    var type = 1;
    if(iid.endsWith("counts")){
      try{
        count = parseInt($(inputs[i]).val());
      }catch(e){}
    }
    if(sid.endsWith("note_type")){
      var sel=$(selects[i]).find("option:selected");
      try{
        type=parseInt(sel.text());
      }catch(e){}
    }
    console.log(type , newinp[i]);
    if (newinp[i] && type) {
      total+=newinp[i]*type;
    }

  }
  var openbal = $("#id_opening_balance").val();
  if (parseInt(openbal) === total) {
    console.log("Equals");
    $("#formsubmit").submit();

  }
  else {
    alert("total: "+total +" doesnt match to opening balance ");
  }


}
</script>



{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
<h1>Main page</h1>
<ul>
  <li>{{object.cashier.username}}</li>
  <li>{{object.counter_id}}</li>
</ul>

  <h3>Opening balance</h3>
  {{object.opening_balance}}
  <table>

      <tr>
        <th>Note name</th>
        <th>Value</th>
        <th>counts</th>
      </tr>
      <tbody id="opening">
        {% for i in object.cash_objects %}
        {% if i.is_customer == False %}
          <tr>
            <td>{{i.note_type.name}}</td>
            <td>{{i.note_type.value}}</td>
            <td>{{i.counts}}</td>
          </tr>
        {% endif %}
        {% endfor %}
      </tbody>
  </table>
<p></p>
<h3>Current Balance</h3>
<table>
  <tr>
    <th>Note name</th>
    <th>Value</th>
    <th>counts</th>
  </tr>
  <tbody id="current">
    {% for i in denom %}

     <tr>
       <td>{{i.name}}</td>
       <td>{{i.value}}</td>
       <td>{% for j in cash %}
         {% if i.value == j.note_type.value %}
         {{j.counts}}
         {% endif %}
         {% endfor %}
       </td>
     </tr>

   {% endfor %}

  </tbody>

</table>

{% if  %}
<a href="{% url 'c_payment' bid=object.id %}">payments</a>


{% endblock %}
{% block extrajs %}

<script>
  var arrtype =[];
  var arrcount =[];
  (function(){
    var opening = $("#opening");
    console.log(opening);
    var trs = opening.find("tr");
    console.log(trs);
    var tds = trs.find("td");
    console.log(tds);
    var count =0;

    for(var i=0;i<tds.length;i++){
      if(count ===1 || count ===2){
        console.log($(tds[i]).html());
        if(count===1){
          arrtype.push($(tds[i]).html());
        }else if(count === 2){
          arrcount.push($(tds[i]).html());
        }

        if(count===2)
        count = -1;
      }
      count++;

    }
    console.log(arrtype+"---------"+arrcount);

  })();



</script>

{% endblock %}

templates/denomination_form.html
{% extends 'base.html' %}
{% block title %} denomination form {% endblock %}

{% block content %}
<h1 class="text-center">denomination form</h1>
<form method="post">

  {% csrf_token %}
  {% for field in form %}
      <div class="form-group row">
          <div class="col-sm-4">
              {{ field.label_tag }}
              {% if field.field.required %}
                  <span class="text-danger">*</span>
              {% endif %}<br>
          </div>
          <div class="col-sm-8">
              {{ field }}
          </div>
      </div>
      {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
      {% endfor %}
  {% endfor %}

<h1 class="text-center">Cash Form </h1>

  <div class="row">
        {% if formset.errors %}
        <div class="col-sm-8 text-danger">{{ formset.non_field_errors }}</div>
        {% endif %}
    </div>
    {% for f in formset.forms %}
    {% if f.errors %}
    <div class="col-sm-8 text-danger" >{{ f.non_field_errors }}</div>
    {% endif %}
    <div id="{{ formset.prefix }}-row"
         style="padding-bottom:6px; border-bottom:1px dotted #ccc; margin-bottom:6px;">
        {% for field in f %}
        {% if field not in f.hidden_fields %}
        <div class="form-group row">
            <div class="col-sm-4 ">
                {{ field.label_tag }}{% if field.field.required %}
                <span class="text-danger"> *</span>{% endif %}
            </div>
            <div class="col-md-8">
                {{ field }}
            </div>
        </div>
        {% endif %}
        {% if field.help_text %}
        <div class="col-sm-8 text-success"><i
                class="fa fa-info-circle"></i> {{ field.help_text }}</div>
        {% endif %}
        {% if field.errors %}
        <div class="col-sm-8 text-danger" >{{ field.errors }}
        </div>
        {% endif %}
        {% for fld in f.hidden_fields %}
        {{ fld }}{% endfor %}
        {% if f.instance.pk %}
        {{ f.DELETE }}
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}

     {{ formset.management_form }}
    <div class="row">
        <div class="col-md-12 block">
            <button type="submit"  class="btn btn-primary mt-4">Submit</button>
        </div>
    </div>
</form>


{% endblock %}

{% block extrajs %}
<script>
        $("#visit_time").prop("readonly", true);
    </script>
<script>
   try {
        var inputs = document.getElementsByTagName("input");
        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].getAttribute("type") === "checkbox") {
                if (!inputs[i].getAttribute("id").includes("DELETE")) {
                    inputs[i].setAttribute("data-toggle", "toggle");
                    inputs[i].setAttribute("data-size", "small");
                    inputs[i].setAttribute("data-on", "<i class='ti-check-box'></i> Yes");
                    inputs[i].setAttribute("data-off", "<i class='ti-close'></i> No");
                }
            } else if (inputs[i].getAttribute("type") === "radio") {

            } else {
                inputs[i].classList.add("form-control");
                try {
                    var placeholder = $(inputs[i].closest('.col-sm-8')).parent().find("div>label").text();
                    if (placeholder === null || placeholder === "") {
                        placeholder = $(inputs[i].closest('.col-sm-12')).parent().find("div>label").text();
                    }
                    if (inputs[i].getAttribute("placeholder") === null) {
                        inputs[i].setAttribute("placeholder", placeholder);
                    }
                } catch (e) {

                }

            }
        }
    } catch (e) {
        log(e)
    }

    try {
        var selects = document.getElementsByTagName("select");
        for (var i = 0; i < selects.length; i++) {
            selects[i].classList.add("form-control");
            selects[i].classList.add("single-select");
        }
    } catch (e) {
        log(e)
    }


    try {
        $(".single-select").select2();
    } catch (e) {

    }

    try {
        var tareas = document.getElementsByTagName("textarea");
        for (var i = 0; i < tareas.length; i++) {
            tareas[i].classList.add("form-control");
            tareas[i].rows = "3";

            try {
                var placeholder = $(tareas[i].closest('.col-sm-8')).parent().find("div>label").text();
                if (placeholder === null || placeholder === "") {
                    placeholder = $(tareas[i].closest('.col-sm-12')).parent().find("div>label").text();
                }

                tareas[i].setAttribute("placeholder", placeholder);
            } catch (e) {

            }
        }
    } catch (e) {
        log(e)
    }

    try {
        var parent = $('input:checkbox[id $= "-DELETE"]').closest(".btn");
        parent.hide();
    } catch (e) {
        console.log("Oops, something went wrong!");
    }
</script>
<script type="text/javascript">
    $(function () {
        $('*[id*=row]').formset({
            extraClasses: ['row1', 'row2', 'row3']
        });
    })
</script>
{% endblock %}

templates/department_form.html
{% extends 'base.html' %}
{% block title %}Add department{% endblock %}
{% block content %}
<h1>Department Form</h1>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="" value="Save">
</form>
{% endblock %}

templates/facebook.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <script
			  src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
			  integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
			  crossorigin="anonymous"></script>


    <title>Facebook</title>
  </head>
  <body>

  </body>
</html>

templates/grid.html
{% extends 'base.html' %}
{% block content %}
<h3>Current Status</h3>
<table class="table">
  <tr>
    <th>Value</th>
    {% for i in cash %}
    <th >{{i.note_type.value}} x</th>
    {% endfor %}
  </tr>
  <tr>
    <td>Counts</td>
    {% for i in cash %}
      <td>{{i.counts}}</td>
    {% endfor %}
  </tr>
</table>
<p></p>
<form method="post">
<div class="row">
  {% csrf_token %}
  <div class="col-lg-6 col-md-6 text-center">
    <h1>Customer Pay</h1>

    {% for i in obj %}
    
    <input type="hidden" name="note" value="{{i}}">
    <label for="note" >{{i}}</label>x
    <input type="number" name="counts" value="">
    <p></p>

    {% endfor %}
  </div>



  <div class="col-lg-6 col-md-6 text-center">
    <h1>Returns</h1>
    {% for i in obj %}
    <input type="hidden" name="return_note" value="{{i}}">
    <label for="note" >{{i}}</label>x
    <input type="number" name="return_counts" value="">
    <p></p>

    {% endfor %}
  </div>

</div>
<input type="submit" name="" value="pay">

</form>



{% endblock %}
{% block extrajs %}
<!-- <script>
  function submit(){
    var inp = $("input");
    var lab = $("label");
    console.log(inp);
    console.log(lab);
    $.post("/pay_cash/",
    {
      inp: inp,
      lab: lab,
    }
    )
    console.log(inp);
    console.log(lab);
    var total = 0;
    for(var i =0;i<inp.length;i++){
      console.log($(lab[i]).html());
      console.log($(inp[i]).val());
      var amt = parseInt($(lab[i]).html());
      var count = parseInt($(inp[i]).val());
      if(count){
        total += amt*count;
      console.log("amt---" +total);
      $.post("/pay_cash/",
      {
        value:$(lab[i]).html(),
        count:$(inp[i]).val()

      },
      )
    }

</script> -->


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}  index {% endblock %}

{% block content %}
<h1>index</h1>

{% endblock %}

templates/main_dash.html
{% extends 'base.html' %}
{% block content %}
<h1>Dash Screen</h1>
<table class="table">
  <tr>
    <th>Value</th>
    {% for i in cash %}
    <th >{{i.note_type.value}} x</th>
    {% endfor %}
    <th></th>
  </tr>
  <tr>
    <td>Counts</td>
    {% for i in cash %}
      <td>{{i.counts}}</td>
    {% endfor %}
  </tr>
</table>
<p></p>
<table class="table">
  <tr>
    <th>Opening Balance</th>
    <th>Current Balance</th>
    <th>Profit</th>
  </tr>
  <tr>
    <td>{{open.amount}}</td>
    <td>{{current.amount}}</td>
    <td>{{profit}}</td>
  </tr>
</table>
<a href="{% url 'grid' bill=bill %}">
<button type="button" name="button">
Payments
</button>
</a>


{% endblock %}

templates/opening_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Bill Counter</h1>
<form method="post">
  {% csrf_token %}
  <label for="">billing counter id</label>
  <input type="text" name="bill" value="">
  <p></p>
  {% for i in obj %}
  <input type="hidden" name="note" value="{{i}}">
  <label for="note" >{{i}}</label>x
  <input type="number" name="counts" value="">
  <p></p>

  {% endfor %}
  <input type="submit" name="" value="login">
</form>



{% endblock %}